(function(){
  const cfg=window.MULTI_EVENT_CONFIG||{};
  const endpoint=cfg.ENDPOINT||'';
  function assertEndpoint(){if(!endpoint||endpoint.includes('PASTE_NEW_'))throw new Error('The new Apps Script endpoint has not been configured in site-config.js.');}
  async function get(params){assertEndpoint();const u=new URL(endpoint);Object.entries(params||{}).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u.toString());return r.json();}
  async function post(body){assertEndpoint();const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body||{})});return r.json();}
  function qs(name){return new URLSearchParams(location.search).get(name)||''}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function money(n,s='$'){return s+(Number(n)||0).toLocaleString(undefined,{minimumFractionDigits:0,maximumFractionDigits:2})}
  function applyBrand(e){if(!e)return;document.documentElement.style.setProperty('--green',e.PrimaryColor||'#0b3d24');document.documentElement.style.setProperty('--gold',e.GoldColor||'#c9a24b');}
  async function loadEvents(){const d=await get({action:'events'});if(!d.ok)throw new Error(d.error||'Could not load events.');return d.events||[]}
  async function loadEvent(id){const d=await get({action:'config',event:id});if(!d.ok)throw new Error(d.error||'Could not load event.');applyBrand(d.event);return d;}
  function image(src){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=src;});}
  function wrap(ctx,text,x,y,maxWidth,lineHeight){let line='';String(text||'').split(/\s+/).forEach(w=>{const t=line+w+' ';if(ctx.measureText(t).width>maxWidth&&line){ctx.fillText(line,x,y);line=w+' ';y+=lineHeight}else line=t});if(line)ctx.fillText(line,x,y);return y;}
  function qr(ctx,text,x,y,size){if(typeof qrcode==='undefined')throw new Error('QR generator did not load.');const q=qrcode(0,'M');q.addData(text);q.make();const n=q.getModuleCount(),cell=size/n;ctx.fillStyle='#fff';ctx.fillRect(x-8,y-8,size+16,size+16);ctx.fillStyle='#000';for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(q.isDark(r,c))ctx.fillRect(x+c*cell,y+r*cell,cell+.4,cell+.4)}
  async function renderTicket(canvas,e,tiers,tier,serial,token){
    const W=1600,H=640;canvas.width=W;canvas.height=H;const ctx=canvas.getContext('2d');const green=e.PrimaryColor||'#0b3d24',gold=e.GoldColor||'#c9a24b',cream='#faf7ef',stubX=W*.78;const ti=tiers[tier]||{label:tier,price:0};
    if(e.BackgroundURL){try{const bg=await image(e.BackgroundURL);ctx.drawImage(bg,0,0,W,H);ctx.fillStyle='rgba(255,255,255,.78)';ctx.fillRect(0,0,stubX,H)}catch(_){ctx.fillStyle=cream;ctx.fillRect(0,0,W,H)}}else{ctx.fillStyle=cream;ctx.fillRect(0,0,W,H)}
    if(e.LogoURL){try{const wm=await image(e.LogoURL);ctx.save();ctx.globalAlpha=.075;const sz=430;ctx.drawImage(wm,stubX/2-sz/2,H/2-sz/2,sz,sz);ctx.restore()}catch(_){}}
    ctx.strokeStyle=gold;ctx.lineWidth=4;ctx.strokeRect(6,6,W-12,H-12);ctx.fillStyle=cream;ctx.fillRect(stubX,6,W-stubX-6,H-12);ctx.setLineDash([7,7]);ctx.strokeStyle='#bfb7a4';ctx.beginPath();ctx.moveTo(stubX,6);ctx.lineTo(stubX,H-6);ctx.stroke();ctx.setLineDash([]);
    ctx.fillStyle=green;ctx.fillRect(stubX,6,W-stubX-6,60);ctx.fillStyle='#fff';ctx.font='700 20px Segoe UI';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('ADMISSION STUB',stubX+(W-stubX)/2,36);const cx=stubX+(W-stubX)/2;
    ctx.fillStyle=green;ctx.font='700 26px Segoe UI';ctx.fillText(String(ti.label||tier).toUpperCase(),cx,110);ctx.fillStyle=gold;ctx.font='700 40px Segoe UI';ctx.fillText((e.CurrencySymbol||'$')+(Number(ti.price)||0),cx,165);ctx.fillStyle='#333';ctx.font='700 18px Segoe UI';ctx.fillText(/double/i.test(ti.label)?'ADMIT TWO':'ADMIT ONE',cx,200);qr(ctx,token||serial,cx-75,220,150);ctx.fillStyle=green;ctx.font='700 14px Segoe UI';ctx.fillText('SERIAL NO.',cx,400);ctx.fillStyle='#000';ctx.font='700 30px Segoe UI';ctx.fillText(serial,cx,435);
    const lx=100,ly=90,lr=55;if(e.LogoURL){try{const logo=await image(e.LogoURL);ctx.save();ctx.beginPath();ctx.arc(lx,ly,lr,0,Math.PI*2);ctx.clip();ctx.drawImage(logo,lx-lr,ly-lr,lr*2,lr*2);ctx.restore()}catch(_){fallbackLogo(ctx,lx,ly,lr,green,e)}}else fallbackLogo(ctx,lx,ly,lr,green,e);
    const x=190;ctx.textAlign='left';ctx.textBaseline='alphabetic';ctx.fillStyle=green;ctx.font='700 22px Segoe UI';ctx.fillText(String(e.OrgName||'').toUpperCase(),x,48);ctx.fillStyle='#000';ctx.font='700 34px Segoe UI';ctx.fillText(String(e.ChapterName||'').toUpperCase(),x,88);ctx.strokeStyle='#d99a5b';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,102);ctx.lineTo(stubX-40,102);ctx.stroke();ctx.fillStyle=gold;ctx.font='700 30px Georgia';ctx.fillText(e.EventTitle||'',x,148);if(e.Tagline){ctx.fillStyle='#22399a';ctx.font='italic 16px Segoe UI';wrap(ctx,e.Tagline,x,176,stubX-x-45,20)}
    let y=226;ctx.fillStyle='#1a3fa0';ctx.font='700 16px Segoe UI';ctx.fillText('📅 '+(e.EventDate||''),x,y);y+=34;ctx.fillText('🕕 '+(e.EventTime||''),x,y);y+=34;ctx.fillText('📍 '+(e.VenueName||''),x,y);y+=25;ctx.fillStyle='#333';ctx.font='400 14px Segoe UI';y=wrap(ctx,e.VenueAddress||'',x,y,stubX-x-55,19)+35;if(e.DressCode){ctx.fillStyle='#000';ctx.font='700 15px Segoe UI';ctx.fillText('DRESS CODE: '+String(e.DressCode).toUpperCase(),x,y)}
    const fy=H-70;ctx.fillStyle=green;ctx.fillRect(10,fy,stubX-16,60);ctx.fillStyle=gold;ctx.font='700 13px Segoe UI';ctx.textAlign='left';ctx.fillText('FOR MORE INFO: '+(e.WebsiteURL||''),30,fy+25);ctx.fillStyle='#fff';ctx.font='400 13px Segoe UI';ctx.fillText('CONTACT: '+(e.ContactPhone||''),30,fy+45);ctx.textAlign='right';ctx.fillText(e.FooterLegalText||'Ticket must be presented for admission',stubX-30,fy+35);
  }
  function fallbackLogo(ctx,cx,cy,r,color,e){ctx.save();ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();ctx.fillStyle='#fff';ctx.font='700 26px Segoe UI';ctx.textAlign='center';ctx.textBaseline='middle';const t=(e.ChapterName||e.EventID||'EV').match(/\b\w/g)||['E','V'];ctx.fillText(t.slice(0,2).join('').toUpperCase(),cx,cy);ctx.restore()}
  window.MultiTickets={endpoint,get,post,qs,esc,money,applyBrand,loadEvents,loadEvent,renderTicket};
})();
